### ISSUE TITLE
Create SignalR Hub

### ISSUE THREAD

**Issue by sonntag-philipp** [sonntag-philipp/MediaSync-Web#2]
**Hub Fkts.**
AwaitPlay(timeStamp: double, videoId: string)
- Fügt den Client zu einer Liste hinzu. Die Liste besteht aus wartenden Clients. 
- Checkt den Status der restlichen Clients
- Wenn Video oder timeStamp unterschiedlich werden die jeweiligen Clients geupdated

JoinRoom(roomName: string)
- Bündelt Clients in eine Gruppe
- Play, Pause und SeekTo werden gruppiert ausgeführt um eine Gruppe zu starten

Pause()
- Pausiert alle Clients im Raum

**Client Fkts.**
Play()

Pause()

SeekTo(timeStamp: double)
- Sprint im Client an eine bestimmte stelle
- Setzt den Status des Clients auf not ready

Navigate(videoId: string)
- Lädt das jeweilige Video im Client und invoked AwaitPlay im Hub wenn buffer fertig ist

GetStatus()
- Returns {time: number, videoId: string}
- Current client state

**Comment by SoerenDaenekas** [comment]
Client A sendet AwaitPlay(1, "AAA") -> Alle Clients gehen auf das Video mit timestamp
Client B sendet AwaitPlay(23, "BBB") -> Das ist weil, der die Memo zu spät bekommen hat.

**Comment by sonntag-philipp** [comment]
![Youtube-Sync](https://user-images.githubusercontent.com/31292378/77082667-b22a1980-69fc-11ea-90b3-a43c0844662c.png)

🤔
